name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre_job:
    continue-on-error: true
    name: "Determine already built commit"
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          skip_after_successful_duplicate: 'true'

  lint:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@2.26.0
        with:
          php-version: 8.2
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run coding standards
        run: composer lint:cs

      - name: Run static analysis
        run: composer lint:phpstan

  tests:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    name: "Tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@2.26.0
        with:
          php-version: 8.2
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run tests
        run: composer test

      - name: Run infection
        run: composer mutation-testing
